### PR TITLE
Per the legal bug, adding some additional details

### PR DESCRIPTION
**Pull request by MattGrimes**

### CODE REVIEW

**Comment by mythmon** [comment]
Which bug is this in reference to? Also, what is this file for? As far as I can tell, it isn't used by any code, and the actual data is in [`data/recomendation/localData.json`](https://github.com/MattGrimes/security-advisor-shield-study/blob/c9c05954b9ebf6e027424ee0f43556c1d255263f/data/recommendation/localData.json). That file is json though, so we can't have comments like this.

**Comment by MattGrimes** [comment]
In the consent page we reference the fact that we are collecting data on "your visits to some popular websites." Legal has asked that we make that a link to a list of which pages this applies to.

**Comment by mythmon** [comment]
That's not really what is happening here, then. The list of sites is dynamic, based on [api respones from haveibeenpwned.com](https://github.com/mozilla/security-advisor-shield-study/blob/master/lib/Advisor.js#L191). We can't make a static list of these sites.

Also, can you reference the bug number? It helps a lot to tie PRs to bugs.

**Comment by MattGrimes** [comment]
Correct. The list is generated dynamically. Since we can't (easily?) show the list of sites generated dynamically in an easy to consume way for the casually interested party that might be reading the consent page, the legal team asked us to just create a list of the sites and put a date that they were generated since it might have changed since then. This is a case of not wanting to give away too much about the study and biasing the results balanced against doing our due diligence in informing users about what we are collecting.

https://bugzilla.mozilla.org/show_bug.cgi?id=1295238

**Comment by mythmon** [comment]
Ok, that makes sense. In that case, the date on the file should be August 23rd, since [that was the last time it was updated](https://github.com/MattGrimes/security-advisor-shield-study/commits/c9c05954b9ebf6e027424ee0f43556c1d255263f/domains.txt). We should file a bug to make script that updates this information and the date, so it is easy to do in the future.

**Comment by mythmon** [comment]
Thanks for working through this with me. I don't like merging things I don't have context for, so the back and forth really helps.

r+

**Pull request merged**
